source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'THJAlertController_Example', :exclusive => true do
  pod "THJAlertController", :path => "../"
end

target 'THJAlertController_Tests', :exclusive => true do
  pod "THJAlertController", :path => "../"

  
end
